esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

esphome:
  name: "Senhus SG-1C"
  name_add_mac_suffix: True
  platformio_options:
    board_build.flash_mode: dio

api:

ota:
- platform: esphome

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # fast_connect: True

  ap:
    ssid: "Senhus SG-1C"

captive_portal:

web_server:
  port: 80

uart:
  tx_pin: GPIO8 
  rx_pin: GPIO7
  baud_rate: 256000

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Occupancy or Movement
    has_moving_target:
      name: Movement
    has_still_target:
      name: Occupancy

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Occupancy Distance
    moving_energy:
      name: Moving Certainty
    still_energy:
      name: Occupancy Certainty


number:
  - platform: ld2410
    timeout:
      name: Clearence Time
    max_move_distance_gate:
      name: Max Movement Detection Range
    max_still_distance_gate:
      name: Max Presence Detection Range
    g0:
      move_threshold:
        name: 0m Movement Threshold
      still_threshold:
        name: 0m Occupancy threshold
    g1:
      move_threshold:
        name: 1m Movement Threshold
      still_threshold:
        name: 1m Occupancy threshold
    g2:
      move_threshold:
        name: 2m Movement Threshold
      still_threshold:
        name: 2m Occupancy threshold
    g3:
      move_threshold:
        name: 3m Movement Threshold
      still_threshold:
        name: 3m Occupancy threshold
    g4:
      move_threshold:
        name: 4m Movement Threshold
      still_threshold:
        name: 4m Occupancy threshold
    g5:
      move_threshold:
        name: 5m Movement Threshold
      still_threshold:
        name: 5m Occupancy threshold
    g6:
      move_threshold:
        name: 6m Movement Threshold
      still_threshold:
        name: 6m Occupancy threshold
    g7:
      move_threshold:
        name: 7m Movement Threshold
      still_threshold:
        name: 7m Occupancy threshold
    g8:
      move_threshold:
        name: 8m Movement Threshold
      still_threshold:
        name: 8m Occupancy threshold